version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
    - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
      - ./data_dump.json:/code/data_dump.json
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

volumes:
  postgres_data:
